---
info:
  title: Network Interface
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/network_interface
  x-cortex-tag: network-interface
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
openapi: 3.0.1
servers:
- url: "/"
